DROP TABLE IF EXISTS PLAYERS;

CREATE TABLE PLAYERS (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    NAME VARCHAR(250) NOT NULL,
    SURNAME VARCHAR(250) NOT NULL,
    YEAR_BIRTH INT DEFAULT NULL
);

INSERT INTO PLAYERS (NAME, SURNAME, YEAR_BIRTH) VALUES
    ('Mario', 'Rossi', 1992),
    ('Bill', 'Gates', null),
    ('Folrunsho', 'Alakija', 2008);